### PR TITLE
Create lumeos

### PR DESCRIPTION
**Pull request by douglumeos**

### CODE REVIEW

**Comment by douglumeos** [comment]
Can you please add this info to the airdrops list?

**Comment by WarrickFitz** [comment]
mm .. it should have been added when I merged your pull request. I'm looking into it now.

**Comment by WarrickFitz** [comment]
I've added it, looks like you added a whole new file instead of editing the airdrop page. You should see it now though.

**Comment by douglumeos** [comment]
Thank you Warrick! Cheers

**Pull request merged**
